### ISSUE TITLE
Battle with the elves collapse

### ISSUE THREAD

**Issue by DaZaiZai** [StrangeOne101/PixelTweaks#19]
## Description
[Describe the bug]
Battle with the elves collapse
## Context
Pixelmon Version: 9.1.11
PixelTweaks Version: 1.10.1
Server or Single Player: Single Player

Additional Context:
java.lang.NoSuchFieldError: BATTLE_MUSIC
	at com.pixelmonmod.pixelmon.client.music.BattleMusic.startBattleMusic(BattleMusic.java:633) ~[pixelmon:1.16.5-9.1.11] {re:mixin,re:classloading,pl:mixin:APP:mixins.pixeltweaks.json:client.BattleMusicMixin,pl:mixin:A}
	at com.pixelmonmod.pixelmon.comm.packetHandlers.battles.music.PlayBattleMusicPacket.handlePacket(PlayBattleMusicPacket.java:69) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at com.pixelmonmod.pixelmon.comm.data.AbstractPixelmonPacket.lambda$handle$0(AbstractPixelmonPacket.java:49) ~[pixelmon:1.16.5-9.1.11] {re:classloading,re:mixin}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[forge:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.pixelmonmod.pixelmon.comm.data.AbstractPixelmonPacket.handle(AbstractPixelmonPacket.java:48) ~[pixelmon:1.16.5-9.1.11] {re:classloading,re:mixin}
	at com.pixelmonmod.pixelmon.comm.PacketRegistry.handle(PacketRegistry.java:494) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at com.pixelmonmod.pixelmon.network.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_401] {}
	at com.pixelmonmod.pixelmon.network.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at com.pixelmonmod.pixelmon.network.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at com.pixelmonmod.pixelmon.network.SimpleChannel.networkEventListener(SimpleChannel.java:78) ~[pixelmon:1.16.5-9.1.11] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_401] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[forge:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[云上宝可梦.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_401] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_401] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_401] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.41.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_401] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_401] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_401] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?] {}

**Comment by StrangeOne101** [comment]
This was fixed in 1.10.2 of PixelTweaks. Update to that version
